//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSWordpiCite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("school/Registration.aspx")]
        public string URI_REGISTER {
            get {
                return ((string)(this["URI_REGISTER"]));
            }
            set {
                this["URI_REGISTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("school/ResetPassword.aspx")]
        public string URI_FORGOTPASSWORD {
            get {
                return ((string)(this["URI_FORGOTPASSWORD"]));
            }
            set {
                this["URI_FORGOTPASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int INPUTEMAIL_WIDTH_DEFAULT {
            get {
                return ((int)(this["INPUTEMAIL_WIDTH_DEFAULT"]));
            }
            set {
                this["INPUTEMAIL_WIDTH_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int INPUTPASSWORD_WIDTH_DEFAULT {
            get {
                return ((int)(this["INPUTPASSWORD_WIDTH_DEFAULT"]));
            }
            set {
                this["INPUTPASSWORD_WIDTH_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Word (Windows)")]
        public string USERAGENT {
            get {
                return ((string)(this["USERAGENT"]));
            }
            set {
                this["USERAGENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PROXY_SETTING {
            get {
                return ((string)(this["PROXY_SETTING"]));
            }
            set {
                this["PROXY_SETTING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Handlers/SyncDataHandler.ashx")]
        public string URI_LOCALDATASERVICE {
            get {
                return ((string)(this["URI_LOCALDATASERVICE"]));
            }
            set {
                this["URI_LOCALDATASERVICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NormalFolder")]
        public string IMAGEKEY_NORMALFOLDER {
            get {
                return ((string)(this["IMAGEKEY_NORMALFOLDER"]));
            }
            set {
                this["IMAGEKEY_NORMALFOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PublicationFolder")]
        public string IMAGEKEY_PUBLICATIONFOLDER {
            get {
                return ((string)(this["IMAGEKEY_PUBLICATIONFOLDER"]));
            }
            set {
                this["IMAGEKEY_PUBLICATIONFOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SharedCollectionFolder")]
        public string IMAGEKEY_SHAREDCOLLECTION {
            get {
                return ((string)(this["IMAGEKEY_SHAREDCOLLECTION"]));
            }
            set {
                this["IMAGEKEY_SHAREDCOLLECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AllItems")]
        public string IMAGEKEY_ALLITEMS {
            get {
                return ((string)(this["IMAGEKEY_ALLITEMS"]));
            }
            set {
                this["IMAGEKEY_ALLITEMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RecycleBin")]
        public string IMAGEKEY_RECYCLEBIN {
            get {
                return ((string)(this["IMAGEKEY_RECYCLEBIN"]));
            }
            set {
                this["IMAGEKEY_RECYCLEBIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WizAdd")]
        public string IMAGEKEY_WIZADD {
            get {
                return ((string)(this["IMAGEKEY_WIZADD"]));
            }
            set {
                this["IMAGEKEY_WIZADD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int MASTER_TREEVIEW_HEIGHT_DEFAULT {
            get {
                return ((int)(this["MASTER_TREEVIEW_HEIGHT_DEFAULT"]));
            }
            set {
                this["MASTER_TREEVIEW_HEIGHT_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MASTER_LISTITEMS_YEAR_WIDTH_DEFAULT {
            get {
                return ((int)(this["MASTER_LISTITEMS_YEAR_WIDTH_DEFAULT"]));
            }
            set {
                this["MASTER_LISTITEMS_YEAR_WIDTH_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20100101000000")]
        public long USER_LASTDATASYNC {
            get {
                return ((long)(this["USER_LASTDATASYNC"]));
            }
            set {
                this["USER_LASTDATASYNC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USER_AUTHENTICATION {
            get {
                return ((string)(this["USER_AUTHENTICATION"]));
            }
            set {
                this["USER_AUTHENTICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USER_REMEMBERME {
            get {
                return ((bool)(this["USER_REMEMBERME"]));
            }
            set {
                this["USER_REMEMBERME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DOCK_POSITION {
            get {
                return ((int)(this["DOCK_POSITION"]));
            }
            set {
                this["DOCK_POSITION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int CUSTOMPANE_HEIGHT_DEFAULT {
            get {
                return ((int)(this["CUSTOMPANE_HEIGHT_DEFAULT"]));
            }
            set {
                this["CUSTOMPANE_HEIGHT_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DEFAULT_REMEMBERME {
            get {
                return ((bool)(this["DEFAULT_REMEMBERME"]));
            }
            set {
                this["DEFAULT_REMEMBERME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DEFAULT_MINLENGTH_INPUTSEARCH {
            get {
                return ((int)(this["DEFAULT_MINLENGTH_INPUTSEARCH"]));
            }
            set {
                this["DEFAULT_MINLENGTH_INPUTSEARCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEFAULT_LANGUAGE {
            get {
                return ((int)(this["DEFAULT_LANGUAGE"]));
            }
            set {
                this["DEFAULT_LANGUAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_LOGIN_EMAIL {
            get {
                return ((string)(this["LAST_LOGIN_EMAIL"]));
            }
            set {
                this["LAST_LOGIN_EMAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DEFAULT_SORTBY {
            get {
                return ((int)(this["DEFAULT_SORTBY"]));
            }
            set {
                this["DEFAULT_SORTBY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double MASTER_VERTICAL_SPLITTERPARENT_RATIO {
            get {
                return ((double)(this["MASTER_VERTICAL_SPLITTERPARENT_RATIO"]));
            }
            set {
                this["MASTER_VERTICAL_SPLITTERPARENT_RATIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double MASTER_VERTICAL_SPLITTERCHILD_RATIO {
            get {
                return ((double)(this["MASTER_VERTICAL_SPLITTERCHILD_RATIO"]));
            }
            set {
                this["MASTER_VERTICAL_SPLITTERCHILD_RATIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double MASTER_HORIZONTAL_SPLITTERPARENT_RATIO {
            get {
                return ((double)(this["MASTER_HORIZONTAL_SPLITTERPARENT_RATIO"]));
            }
            set {
                this["MASTER_HORIZONTAL_SPLITTERPARENT_RATIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.45")]
        public double MASTER_HORIZONTAL_SPLITTERCHILD_RATIO {
            get {
                return ((double)(this["MASTER_HORIZONTAL_SPLITTERCHILD_RATIO"]));
            }
            set {
                this["MASTER_HORIZONTAL_SPLITTERCHILD_RATIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MASTER_PREVIEW_COLLAPSED {
            get {
                return ((bool)(this["MASTER_PREVIEW_COLLAPSED"]));
            }
            set {
                this["MASTER_PREVIEW_COLLAPSED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\πFolio\\Files\\")]
        public string DEFAULT_FILES_FOLDER {
            get {
                return ((string)(this["DEFAULT_FILES_FOLDER"]));
            }
            set {
                this["DEFAULT_FILES_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DEFAULT_RESET {
            get {
                return ((bool)(this["DEFAULT_RESET"]));
            }
            set {
                this["DEFAULT_RESET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("111")]
        public int DEFAULT_FILTER_FIELDS {
            get {
                return ((int)(this["DEFAULT_FILTER_FIELDS"]));
            }
            set {
                this["DEFAULT_FILTER_FIELDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultLogFilePath {
            get {
                return ((string)(this["DefaultLogFilePath"]));
            }
            set {
                this["DefaultLogFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}?style=1&UserID={1}&StyleName={2}")]
        public string FORMAT_URL_STYLEEDITOR {
            get {
                return ((string)(this["FORMAT_URL_STYLEEDITOR"]));
            }
            set {
                this["FORMAT_URL_STYLEEDITOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int DEFAULT_STYLECHOOSER_WIDTH {
            get {
                return ((int)(this["DEFAULT_STYLECHOOSER_WIDTH"]));
            }
            set {
                this["DEFAULT_STYLECHOOSER_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int DEFAULT_STYLECHOOSER_HEIGHT {
            get {
                return ((int)(this["DEFAULT_STYLECHOOSER_HEIGHT"]));
            }
            set {
                this["DEFAULT_STYLECHOOSER_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}?citation=1&ver=3&ItemID={1}&UserID={2}&AccessCode={3}&CitationSuffix=")]
        public string FORMAT_URL_CITEDITEM {
            get {
                return ((string)(this["FORMAT_URL_CITEDITEM"]));
            }
            set {
                this["FORMAT_URL_CITEDITEM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}?style=1&ver=3&UserID={1}&StyleName={2}")]
        public string FORMAT_URL_CITATIONSTYLE {
            get {
                return ((string)(this["FORMAT_URL_CITATIONSTYLE"]));
            }
            set {
                this["FORMAT_URL_CITATIONSTYLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Handlers/WizFolioShare.ashx")]
        public string URI_LOCALSHARESERVICE {
            get {
                return ((string)(this["URI_LOCALSHARESERVICE"]));
            }
            set {
                this["URI_LOCALSHARESERVICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APA (6th edition)")]
        public string DEFAULT_CITATION_STYLE_NAME {
            get {
                return ((string)(this["DEFAULT_CITATION_STYLE_NAME"]));
            }
            set {
                this["DEFAULT_CITATION_STYLE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int DEFAULT_STYLEEDITOR_WIDTH {
            get {
                return ((int)(this["DEFAULT_STYLEEDITOR_WIDTH"]));
            }
            set {
                this["DEFAULT_STYLEEDITOR_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int DEFAULT_STYLEEDITOR_HEIGHT {
            get {
                return ((int)(this["DEFAULT_STYLEEDITOR_HEIGHT"]));
            }
            set {
                this["DEFAULT_STYLEEDITOR_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_USED_CITATIONSTYLES {
            get {
                return ((string)(this["LAST_USED_CITATIONSTYLES"]));
            }
            set {
                this["LAST_USED_CITATIONSTYLES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int LAST_USED_CITATIONSTYLES_NUMBER {
            get {
                return ((int)(this["LAST_USED_CITATIONSTYLES_NUMBER"]));
            }
            set {
                this["LAST_USED_CITATIONSTYLES_NUMBER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("colleague")]
        public string IMAGEKEY_COLLEAGUE {
            get {
                return ((string)(this["IMAGEKEY_COLLEAGUE"]));
            }
            set {
                this["IMAGEKEY_COLLEAGUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("colleaguelist")]
        public string IMAGEKEY_COLLEAGUELIST {
            get {
                return ((string)(this["IMAGEKEY_COLLEAGUELIST"]));
            }
            set {
                this["IMAGEKEY_COLLEAGUELIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CitedReferences")]
        public string IMAGEKEY_CITEDREFERENCES {
            get {
                return ((string)(this["IMAGEKEY_CITEDREFERENCES"]));
            }
            set {
                this["IMAGEKEY_CITEDREFERENCES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("error.log")]
        public string DefaultLogFileName {
            get {
                return ((string)(this["DefaultLogFileName"]));
            }
            set {
                this["DefaultLogFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Handlers/LoginHandler.ashx")]
        public string URI_LOGINHANDLER {
            get {
                return ((string)(this["URI_LOGINHANDLER"]));
            }
            set {
                this["URI_LOGINHANDLER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Handlers/WizFolioData.ashx")]
        public string URI_ROOTDATAHANDLER {
            get {
                return ((string)(this["URI_ROOTDATAHANDLER"]));
            }
            set {
                this["URI_ROOTDATAHANDLER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Loading")]
        public string IMAGEKEY_LOADING {
            get {
                return ((string)(this["IMAGEKEY_LOADING"]));
            }
            set {
                this["IMAGEKEY_LOADING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Login.aspx?wizcitemode=1&authstr={0}&style=1&userid={1}&stylename={2}")]
        public string URI_LOGINSTYLEEDITOR {
            get {
                return ((string)(this["URI_LOGINSTYLEEDITOR"]));
            }
            set {
                this["URI_LOGINSTYLEEDITOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public int CUSTOMPANE_MINIMUM_WIDTH {
            get {
                return ((int)(this["CUSTOMPANE_MINIMUM_WIDTH"]));
            }
            set {
                this["CUSTOMPANE_MINIMUM_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("390")]
        public int CUSTOMPANE_WIDTH_DEFAULT {
            get {
                return ((int)(this["CUSTOMPANE_WIDTH_DEFAULT"]));
            }
            set {
                this["CUSTOMPANE_WIDTH_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104")]
        public int DEFAULT_PROGRESS_HEIGHT {
            get {
                return ((int)(this["DEFAULT_PROGRESS_HEIGHT"]));
            }
            set {
                this["DEFAULT_PROGRESS_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("260")]
        public int DEFAULT_PROGRESS_WIDTH {
            get {
                return ((int)(this["DEFAULT_PROGRESS_WIDTH"]));
            }
            set {
                this["DEFAULT_PROGRESS_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int MASTER_SPLITPARENT_PANEL1_H_MINHEIGHT {
            get {
                return ((int)(this["MASTER_SPLITPARENT_PANEL1_H_MINHEIGHT"]));
            }
            set {
                this["MASTER_SPLITPARENT_PANEL1_H_MINHEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int MASTER_SPLITPARENT_PANEL2_H_MINHEIGHT {
            get {
                return ((int)(this["MASTER_SPLITPARENT_PANEL2_H_MINHEIGHT"]));
            }
            set {
                this["MASTER_SPLITPARENT_PANEL2_H_MINHEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int MASTER_SPLITCHILD_PANEL1_H_MINHEIGHT {
            get {
                return ((int)(this["MASTER_SPLITCHILD_PANEL1_H_MINHEIGHT"]));
            }
            set {
                this["MASTER_SPLITCHILD_PANEL1_H_MINHEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MASTER_SPLITCHILD_PANEL2_H_MINHEIGHT {
            get {
                return ((int)(this["MASTER_SPLITCHILD_PANEL2_H_MINHEIGHT"]));
            }
            set {
                this["MASTER_SPLITCHILD_PANEL2_H_MINHEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int MASTER_SPLITPARENT_PANEL1_V_MINWIDTH {
            get {
                return ((int)(this["MASTER_SPLITPARENT_PANEL1_V_MINWIDTH"]));
            }
            set {
                this["MASTER_SPLITPARENT_PANEL1_V_MINWIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int MASTER_SPLITPARENT_PANEL2_V_MINWIDTH {
            get {
                return ((int)(this["MASTER_SPLITPARENT_PANEL2_V_MINWIDTH"]));
            }
            set {
                this["MASTER_SPLITPARENT_PANEL2_V_MINWIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public int MASTER_SPLITCHILD_PANEL1_V_MINWIDTH {
            get {
                return ((int)(this["MASTER_SPLITCHILD_PANEL1_V_MINWIDTH"]));
            }
            set {
                this["MASTER_SPLITCHILD_PANEL1_V_MINWIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public int MASTER_SPLITCHILD_PANEL2_V_MINWIDTH {
            get {
                return ((int)(this["MASTER_SPLITCHILD_PANEL2_V_MINWIDTH"]));
            }
            set {
                this["MASTER_SPLITCHILD_PANEL2_V_MINWIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Login.aspx?wizcitemode=1&authstr={0}&referrer={1}")]
        public string URI_LOGINACCESS {
            get {
                return ((string)(this["URI_LOGINACCESS"]));
            }
            set {
                this["URI_LOGINACCESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int DEFAULT_NUMOFCITATIONS_NOREFRESH {
            get {
                return ((int)(this["DEFAULT_NUMOFCITATIONS_NOREFRESH"]));
            }
            set {
                this["DEFAULT_NUMOFCITATIONS_NOREFRESH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int DEFAULT_SCREENTIP_TITLE_WORDLIMIT {
            get {
                return ((int)(this["DEFAULT_SCREENTIP_TITLE_WORDLIMIT"]));
            }
            set {
                this["DEFAULT_SCREENTIP_TITLE_WORDLIMIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int DEFAULT_NUMOFITEMS_PER_LOAD {
            get {
                return ((int)(this["DEFAULT_NUMOFITEMS_PER_LOAD"]));
            }
            set {
                this["DEFAULT_NUMOFITEMS_PER_LOAD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Payment/MySubscriptions.aspx")]
        public string URI_SUBSCRIPTION {
            get {
                return ((string)(this["URI_SUBSCRIPTION"]));
            }
            set {
                this["URI_SUBSCRIPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Citation Tools {0}")]
        public string CUSTOMPANE_TITLE {
            get {
                return ((string)(this["CUSTOMPANE_TITLE"]));
            }
            set {
                this["CUSTOMPANE_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1 beta")]
        public string VERSION {
            get {
                return ((string)(this["VERSION"]));
            }
            set {
                this["VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DEFAULT_SHOWQUICKSTART {
            get {
                return ((bool)(this["DEFAULT_SHOWQUICKSTART"]));
            }
            set {
                this["DEFAULT_SHOWQUICKSTART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://help.pifolio.com/Contents/WizCite4_Tutorial.aspx?content=quickstart&menu=0" +
            "")]
        public string URL_QUICKSTART {
            get {
                return ((string)(this["URL_QUICKSTART"]));
            }
            set {
                this["URL_QUICKSTART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1050")]
        public int DEFAULT_QUICKSTART_WIDTH {
            get {
                return ((int)(this["DEFAULT_QUICKSTART_WIDTH"]));
            }
            set {
                this["DEFAULT_QUICKSTART_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650")]
        public int DEFAULT_QUICKSTART_HEIGHT {
            get {
                return ((int)(this["DEFAULT_QUICKSTART_HEIGHT"]));
            }
            set {
                this["DEFAULT_QUICKSTART_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QUICKSTART_ALLOW_PERMANENTCLOSED {
            get {
                return ((bool)(this["QUICKSTART_ALLOW_PERMANENTCLOSED"]));
            }
            set {
                this["QUICKSTART_ALLOW_PERMANENTCLOSED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PubMedNotificationCat")]
        public string IMAGEKEY_PUBMEDNOTICAT {
            get {
                return ((string)(this["IMAGEKEY_PUBMEDNOTICAT"]));
            }
            set {
                this["IMAGEKEY_PUBMEDNOTICAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PubMedNotification")]
        public string IMAGEKEY_PUBMEDNOTI {
            get {
                return ((string)(this["IMAGEKEY_PUBMEDNOTI"]));
            }
            set {
                this["IMAGEKEY_PUBMEDNOTI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NotificationTime")]
        public string IMAGEKEY_NOTITIME {
            get {
                return ((string)(this["IMAGEKEY_NOTITIME"]));
            }
            set {
                this["IMAGEKEY_NOTITIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PubMedSearch")]
        public string IMAGEKEY_PUBMEDSEARCH {
            get {
                return ((string)(this["IMAGEKEY_PUBMEDSEARCH"]));
            }
            set {
                this["IMAGEKEY_PUBMEDSEARCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ScholarsPortalSearch")]
        public string IMAGEKEY_SCHOLARSPORTALSEARCH {
            get {
                return ((string)(this["IMAGEKEY_SCHOLARSPORTALSEARCH"]));
            }
            set {
                this["IMAGEKEY_SCHOLARSPORTALSEARCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int NUM_OF_SEARCH_RESULTS_PER_PAGE {
            get {
                return ((int)(this["NUM_OF_SEARCH_RESULTS_PER_PAGE"]));
            }
            set {
                this["NUM_OF_SEARCH_RESULTS_PER_PAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FilterImage")]
        public string IMAGEKEY_SEARCHOPTIONS_FILTER {
            get {
                return ((string)(this["IMAGEKEY_SEARCHOPTIONS_FILTER"]));
            }
            set {
                this["IMAGEKEY_SEARCHOPTIONS_FILTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PubMedImage")]
        public string IMAGEKEY_SEARCHOPTIONS_PUBMED {
            get {
                return ((string)(this["IMAGEKEY_SEARCHOPTIONS_PUBMED"]));
            }
            set {
                this["IMAGEKEY_SEARCHOPTIONS_PUBMED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ScholarsPortalImage")]
        public string IMAGEKEY_SEARCHOPTIONS_SCHOLARSPORTAL {
            get {
                return ((string)(this["IMAGEKEY_SEARCHOPTIONS_SCHOLARSPORTAL"]));
            }
            set {
                this["IMAGEKEY_SEARCHOPTIONS_SCHOLARSPORTAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CiteULikeImage")]
        public string IMAGEKEY_SEARCHOPTIONS_CITEULIKE {
            get {
                return ((string)(this["IMAGEKEY_SEARCHOPTIONS_CITEULIKE"]));
            }
            set {
                this["IMAGEKEY_SEARCHOPTIONS_CITEULIKE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorldCatImage")]
        public string IMAGEKEY_SEARCHOPTIONS_WORLDCAT {
            get {
                return ((string)(this["IMAGEKEY_SEARCHOPTIONS_WORLDCAT"]));
            }
            set {
                this["IMAGEKEY_SEARCHOPTIONS_WORLDCAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GoogleScholarImage")]
        public string IMAGEKEY_SEARCHOPTIONS_GOOGLESCHOLAR {
            get {
                return ((string)(this["IMAGEKEY_SEARCHOPTIONS_GOOGLESCHOLAR"]));
            }
            set {
                this["IMAGEKEY_SEARCHOPTIONS_GOOGLESCHOLAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WizSearchImage")]
        public string IMAGEKEY_SEARCHOPTIONS_WIZSEARCH {
            get {
                return ((string)(this["IMAGEKEY_SEARCHOPTIONS_WIZSEARCH"]));
            }
            set {
                this["IMAGEKEY_SEARCHOPTIONS_WIZSEARCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("searchdbimage")]
        public string IMAGEKEY_SEARCHOPTIONS_SEARCHDB {
            get {
                return ((string)(this["IMAGEKEY_SEARCHOPTIONS_SEARCHDB"]));
            }
            set {
                this["IMAGEKEY_SEARCHOPTIONS_SEARCHDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DEFAULT_IS_SORTDIRECTION_ASCENDING {
            get {
                return ((bool)(this["DEFAULT_IS_SORTDIRECTION_ASCENDING"]));
            }
            set {
                this["DEFAULT_IS_SORTDIRECTION_ASCENDING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://root.pifolio.com/")]
        public string URL_ROOTSERVER {
            get {
                return ((string)(this["URL_ROOTSERVER"]));
            }
            set {
                this["URL_ROOTSERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://provider.pifolio.com/file/citationtool/template/")]
        public string URL_TEMPLATE {
            get {
                return ((string)(this["URL_TEMPLATE"]));
            }
            set {
                this["URL_TEMPLATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\πFolio\\Templates\\")]
        public string DEFAULT_TEMPLATE_FOLDER {
            get {
                return ((string)(this["DEFAULT_TEMPLATE_FOLDER"]));
            }
            set {
                this["DEFAULT_TEMPLATE_FOLDER"] = value;
            }
        }
    }
}
