//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSWordpiCite.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSWordpiCite.Lang.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items selected.
        /// </summary>
        internal static string Alert_NoItemSelected_Msg {
            get {
                return ResourceManager.GetString("Alert_NoItemSelected_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more matching references found.
        /// </summary>
        internal static string Alert_NoMoreMatching_Msg {
            get {
                return ResourceManager.GetString("Alert_NoMoreMatching_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Login_Email_Label {
            get {
                return ResourceManager.GetString("Login_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string Login_ForgotPassword_Link {
            get {
                return ResourceManager.GetString("Login_ForgotPassword_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging into πFolio ....
        /// </summary>
        internal static string Login_LoggingIn_Label {
            get {
                return ResourceManager.GetString("Login_LoggingIn_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Login_Button {
            get {
                return ResourceManager.GetString("Login_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citation Tool is unable to access the internet. Please check your network connection..
        /// </summary>
        internal static string Login_NoInternet_Msg {
            get {
                return ResourceManager.GetString("Login_NoInternet_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection detected.
        /// </summary>
        internal static string Login_NoInternet_Title {
            get {
                return ResourceManager.GetString("Login_NoInternet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Password_Label {
            get {
                return ResourceManager.GetString("Login_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string Login_Register_Link {
            get {
                return ResourceManager.GetString("Login_Register_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string Login_RememberMe_CheckBox {
            get {
                return ResourceManager.GetString("Login_RememberMe_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to πFolio.
        /// </summary>
        internal static string Login_Title_Label {
            get {
                return ResourceManager.GetString("Login_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert citation(s).
        /// </summary>
        internal static string Master_BtnCite_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnCite_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to find selected reference\nClick again to jump to the next appearance of the reference..
        /// </summary>
        internal static string Master_BtnHightlight_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnHightlight_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to load more results ....
        /// </summary>
        internal static string Master_BtnMore_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnMore_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide preview.
        /// </summary>
        internal static string Master_BtnPreview_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnPreview_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to search in PubMed database.
        /// </summary>
        internal static string Master_BtnPubMed_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnPubMed_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List cited references in this document.
        /// </summary>
        internal static string Master_BtnRefList_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnRefList_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh citations and reference list in this document.
        /// </summary>
        internal static string Master_BtnRefresh_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnRefresh_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to search in ScholarsPortal database.
        /// </summary>
        internal static string Master_BtnScholarsPortal_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnScholarsPortal_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select database to perform search.
        /// </summary>
        internal static string Master_BtnSearch_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnSearch_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort and Find options.
        /// </summary>
        internal static string Master_BtnSortBy_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnSortBy_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change citation style.
        /// </summary>
        internal static string Master_BtnStyle_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnStyle_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Template.
        /// </summary>
        internal static string Master_BtnTemplate_Tooltip {
            get {
                return ResourceManager.GetString("Master_BtnTemplate_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cited References.
        /// </summary>
        internal static string Master_CitedReferences_Label {
            get {
                return ResourceManager.GetString("Master_CitedReferences_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of the cited references in this document.
        /// </summary>
        internal static string Master_CitedReferences_Tooltip {
            get {
                return ResourceManager.GetString("Master_CitedReferences_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( Type in the query and press Enter to search ).
        /// </summary>
        internal static string Master_ClickEnterToSearch_Label {
            get {
                return ResourceManager.GetString("Master_ClickEnterToSearch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open the file.
        /// </summary>
        internal static string Master_ClickOpen_Tooltip {
            get {
                return ResourceManager.GetString("Master_ClickOpen_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open the link.
        /// </summary>
        internal static string Master_ClickOpenLink_Tooltip {
            get {
                return ResourceManager.GetString("Master_ClickOpenLink_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to load the list of your colleagues.
        /// </summary>
        internal static string Master_ColleagueList_Tooltip {
            get {
                return ResourceManager.GetString("Master_ColleagueList_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Colleagues.
        /// </summary>
        internal static string Master_ColleaguesList_Label {
            get {
                return ResourceManager.GetString("Master_ColleaguesList_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is currently trying to download another file. Please try again later!.
        /// </summary>
        internal static string Master_DownloadingBusy_Label {
            get {
                return ResourceManager.GetString("Master_DownloadingBusy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading in progress.
        /// </summary>
        internal static string Master_DownloadingBusy_Title {
            get {
                return ResourceManager.GetString("Master_DownloadingBusy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading ....
        /// </summary>
        internal static string Master_DownloadingFile_Label {
            get {
                return ResourceManager.GetString("Master_DownloadingFile_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter options.
        /// </summary>
        internal static string Master_Filter_MenuItem {
            get {
                return ResourceManager.GetString("Master_Filter_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        internal static string Master_FilterField_Abstract_Label {
            get {
                return ResourceManager.GetString("Master_FilterField_Abstract_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string Master_FilterField_Authors_Label {
            get {
                return ResourceManager.GetString("Master_FilterField_Authors_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string Master_FilterField_Keywords_Label {
            get {
                return ResourceManager.GetString("Master_FilterField_Keywords_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Master_FilterField_Notes_Label {
            get {
                return ResourceManager.GetString("Master_FilterField_Notes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Year.
        /// </summary>
        internal static string Master_FilterField_PubDate_Label {
            get {
                return ResourceManager.GetString("Master_FilterField_PubDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Master_FilterField_Tags_Label {
            get {
                return ResourceManager.GetString("Master_FilterField_Tags_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Master_FilterField_Title_Label {
            get {
                return ResourceManager.GetString("Master_FilterField_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string Master_FilterField_Title2_Label {
            get {
                return ResourceManager.GetString("Master_FilterField_Title2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide item preview.
        /// </summary>
        internal static string Master_HidePreview_MenuItem {
            get {
                return ResourceManager.GetString("Master_HidePreview_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in PubMed database ....
        /// </summary>
        internal static string Master_InputPubMedSearch_Text {
            get {
                return ResourceManager.GetString("Master_InputPubMedSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in ScholarsPortal database ....
        /// </summary>
        internal static string Master_InputScholarsPortalSearch_Text {
            get {
                return ResourceManager.GetString("Master_InputScholarsPortalSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Cite U Like ....
        /// </summary>
        internal static string Master_InputSearch_CiteULike_Label {
            get {
                return ResourceManager.GetString("Master_InputSearch_CiteULike_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter items in this folder ....
        /// </summary>
        internal static string Master_InputSearch_Filter_Label {
            get {
                return ResourceManager.GetString("Master_InputSearch_Filter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Google Search ....
        /// </summary>
        internal static string Master_InputSearch_GoogleScholar_Label {
            get {
                return ResourceManager.GetString("Master_InputSearch_GoogleScholar_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in PubMed ....
        /// </summary>
        internal static string Master_InputSearch_PubMed_Label {
            get {
                return ResourceManager.GetString("Master_InputSearch_PubMed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Scholars Portal ....
        /// </summary>
        internal static string Master_InputSearch_ScholarsPortal_Label {
            get {
                return ResourceManager.GetString("Master_InputSearch_ScholarsPortal_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter items in this folder ....
        /// </summary>
        internal static string Master_InputSearch_Text {
            get {
                return ResourceManager.GetString("Master_InputSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in πFolio Collections ....
        /// </summary>
        internal static string Master_InputSearch_WizSearch_Label {
            get {
                return ResourceManager.GetString("Master_InputSearch_WizSearch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Word Cat ....
        /// </summary>
        internal static string Master_InputSearch_WorldCat_Label {
            get {
                return ResourceManager.GetString("Master_InputSearch_WorldCat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading folders ....
        /// </summary>
        internal static string Master_LoadingFolders_Label {
            get {
                return ResourceManager.GetString("Master_LoadingFolders_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading items ....
        /// </summary>
        internal static string Master_LoadingItems_Label {
            get {
                return ResourceManager.GetString("Master_LoadingItems_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading items ... ( {0} ).
        /// </summary>
        internal static string Master_LoadingItemsProgress_Label {
            get {
                return ResourceManager.GetString("Master_LoadingItemsProgress_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Master_Logout_Link {
            get {
                return ResourceManager.GetString("Master_Logout_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Library.
        /// </summary>
        internal static string Master_MyCollections_Label {
            get {
                return ResourceManager.GetString("Master_MyCollections_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To avoid prolonged refreshing, auto-refresh is turned off by default when the number of citations reaches {0} items.\nManually refresh after you have completed your citations..
        /// </summary>
        internal static string Master_NoAutoRefresh {
            get {
                return ResourceManager.GetString("Master_NoAutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CitationTool Notification.
        /// </summary>
        internal static string Master_NoAutoRefresh_Title {
            get {
                return ResourceManager.GetString("Master_NoAutoRefresh_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to load the colleague&apos;s sharing folders.
        /// </summary>
        internal static string Master_NodeColleague_Tooltip {
            get {
                return ResourceManager.GetString("Master_NodeColleague_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No items found).
        /// </summary>
        internal static string Master_NoItems_Label {
            get {
                return ResourceManager.GetString("Master_NoItems_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to load more results from PubMed.
        /// </summary>
        internal static string Master_PubMedMore_Tooltip {
            get {
                return ResourceManager.GetString("Master_PubMedMore_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in PubMed.
        /// </summary>
        internal static string Master_PubMedSearch_Label {
            get {
                return ResourceManager.GetString("Master_PubMedSearch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to start searching in PubMed database.
        /// </summary>
        internal static string Master_PubMedSearch_Tooltip {
            get {
                return ResourceManager.GetString("Master_PubMedSearch_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload all folders and items for the latest update.
        /// </summary>
        internal static string Master_Reload_Link {
            get {
                return ResourceManager.GetString("Master_Reload_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to load more results from ScholarsPortal.
        /// </summary>
        internal static string Master_ScholarsPortalMore_Tooltip {
            get {
                return ResourceManager.GetString("Master_ScholarsPortalMore_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in ScholarsPortal.
        /// </summary>
        internal static string Master_ScholarsPortalSearch_Label {
            get {
                return ResourceManager.GetString("Master_ScholarsPortalSearch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to start searching in ScholarsPortal database.
        /// </summary>
        internal static string Master_ScholarsPortalSearch_Tooltip {
            get {
                return ResourceManager.GetString("Master_ScholarsPortalSearch_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        internal static string Master_Search_Label {
            get {
                return ResourceManager.GetString("Master_Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in CiteULike.
        /// </summary>
        internal static string Master_SearchOptions_CiteULike {
            get {
                return ResourceManager.GetString("Master_SearchOptions_CiteULike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter items in this folder.
        /// </summary>
        internal static string Master_SearchOptions_Filter {
            get {
                return ResourceManager.GetString("Master_SearchOptions_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Google Scholar.
        /// </summary>
        internal static string Master_SearchOptions_GoogleScholar {
            get {
                return ResourceManager.GetString("Master_SearchOptions_GoogleScholar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in PubMed.
        /// </summary>
        internal static string Master_SearchOptions_PubMed {
            get {
                return ResourceManager.GetString("Master_SearchOptions_PubMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Scholars Portal.
        /// </summary>
        internal static string Master_SearchOptions_ScholarsPortal {
            get {
                return ResourceManager.GetString("Master_SearchOptions_ScholarsPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in databases.
        /// </summary>
        internal static string Master_SearchOptions_SearchDatabases {
            get {
                return ResourceManager.GetString("Master_SearchOptions_SearchDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in πFolio Collections.
        /// </summary>
        internal static string Master_SearchOptions_WizSearch {
            get {
                return ResourceManager.GetString("Master_SearchOptions_WizSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in WorldCat.
        /// </summary>
        internal static string Master_SearchOptions_WorldCat {
            get {
                return ResourceManager.GetString("Master_SearchOptions_WorldCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item preview.
        /// </summary>
        internal static string Master_ShowPreview_MenuItem {
            get {
                return ResourceManager.GetString("Master_ShowPreview_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort                .
        /// </summary>
        internal static string Master_Sort_MenuItem {
            get {
                return ResourceManager.GetString("Master_Sort_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string Master_SortBy_Author {
            get {
                return ResourceManager.GetString("Master_SortBy_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        internal static string Master_SortBy_ItemType {
            get {
                return ResourceManager.GetString("Master_SortBy_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Name.
        /// </summary>
        internal static string Master_SortBy_Journal {
            get {
                return ResourceManager.GetString("Master_SortBy_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Master_SortBy_Label {
            get {
                return ResourceManager.GetString("Master_SortBy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Master_SortBy_None {
            get {
                return ResourceManager.GetString("Master_SortBy_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Master_SortBy_Title {
            get {
                return ResourceManager.GetString("Master_SortBy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Year.
        /// </summary>
        internal static string Master_SortBy_Year {
            get {
                return ResourceManager.GetString("Master_SortBy_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to go to your πFolio web.
        /// </summary>
        internal static string Master_UserName_Tooltip {
            get {
                return ResourceManager.GetString("Master_UserName_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CitationTool {0}.
        /// </summary>
        internal static string piCite_Ribbon_Button_Label {
            get {
                return ResourceManager.GetString("piCite_Ribbon_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to start CitationTool (ver {0}).
        /// </summary>
        internal static string piCite_Ribbon_Button_ScreenTip {
            get {
                return ResourceManager.GetString("piCite_Ribbon_Button_ScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CitationTool (πFolio Citation Generator) inserts citations from your πFolio account directly into your documents and allows universal compatibility between different word processors..
        /// </summary>
        internal static string piCite_Ribbon_Button_SuperTip {
            get {
                return ResourceManager.GetString("piCite_Ribbon_Button_SuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No items selected).
        /// </summary>
        internal static string Preview_NoItem_Label {
            get {
                return ResourceManager.GetString("Preview_NoItem_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing citation style to &quot;{0}&quot; ....
        /// </summary>
        internal static string Progress_ChangeCitationStyle_Msg {
            get {
                return ResourceManager.GetString("Progress_ChangeCitationStyle_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing citation style.
        /// </summary>
        internal static string Progress_ChangeCitationStyle_Title {
            get {
                return ResourceManager.GetString("Progress_ChangeCitationStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait ....
        /// </summary>
        internal static string Progress_InsertCitation_Msg {
            get {
                return ResourceManager.GetString("Progress_InsertCitation_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting citations.
        /// </summary>
        internal static string Progress_InsertCitation_Title {
            get {
                return ResourceManager.GetString("Progress_InsertCitation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait ....
        /// </summary>
        internal static string Progress_RefreshCitation_Msg {
            get {
                return ResourceManager.GetString("Progress_RefreshCitation_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing citations.
        /// </summary>
        internal static string Progress_RefreshCitation_Title {
            get {
                return ResourceManager.GetString("Progress_RefreshCitation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this Quick Start window again ?.
        /// </summary>
        internal static string QuickStart_ShowNextTime_Msg {
            get {
                return ResourceManager.GetString("QuickStart_ShowNextTime_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to πFolio - Quick Start.
        /// </summary>
        internal static string QuickStart_ShowNextTime_Title {
            get {
                return ResourceManager.GetString("QuickStart_ShowNextTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to πFolio - CitationTool {0} Quick Start.
        /// </summary>
        internal static string QuickStart_Title {
            get {
                return ResourceManager.GetString("QuickStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort ascending.
        /// </summary>
        internal static string SortAscending_Label {
            get {
                return ResourceManager.GetString("SortAscending_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort descending.
        /// </summary>
        internal static string SortDescending_Label {
            get {
                return ResourceManager.GetString("SortDescending_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please enter the password.
        /// </summary>
        internal static string Status_Empty_Password {
            get {
                return ResourceManager.GetString("Status_Empty_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * You have entered an invalid email.
        /// </summary>
        internal static string Status_Invalid_Email {
            get {
                return ResourceManager.GetString("Status_Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * You have entered a wrong email address or password.
        /// </summary>
        internal static string Status_Login_Failed {
            get {
                return ResourceManager.GetString("Status_Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in to WizFolio.
        /// </summary>
        internal static string Status_Login_Success {
            get {
                return ResourceManager.GetString("Status_Login_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply this style.
        /// </summary>
        internal static string StyleChooser_BtnApply_Tooltip {
            get {
                return ResourceManager.GetString("StyleChooser_BtnApply_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close citation style chooser window.
        /// </summary>
        internal static string StyleChooser_BtnClose_Tooltip {
            get {
                return ResourceManager.GetString("StyleChooser_BtnClose_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this style.
        /// </summary>
        internal static string StyleChooser_BtnEdit_Tooltip {
            get {
                return ResourceManager.GetString("StyleChooser_BtnEdit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload the list of citation styles.
        /// </summary>
        internal static string StyleChooser_BtnReload_Tooltip {
            get {
                return ResourceManager.GetString("StyleChooser_BtnReload_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only commonly used citation styles.
        /// </summary>
        internal static string StyleChooser_BtnShowAll_Hide_Tooltip {
            get {
                return ResourceManager.GetString("StyleChooser_BtnShowAll_Hide_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all citation styles.
        /// </summary>
        internal static string StyleChooser_BtnShowAll_Tooltip {
            get {
                return ResourceManager.GetString("StyleChooser_BtnShowAll_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access the full list of over 1000 citation styles, please upgrade to a Premium account or an Institutional account.\nDo you wish to upgrade your account?.
        /// </summary>
        internal static string StyleChooser_BtnShowAll_WarningFreeUser {
            get {
                return ResourceManager.GetString("StyleChooser_BtnShowAll_WarningFreeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade your πFolio account.
        /// </summary>
        internal static string StyleChooser_BtnShowAll_WarningFreeUser_Title {
            get {
                return ResourceManager.GetString("StyleChooser_BtnShowAll_WarningFreeUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No citation styles found).
        /// </summary>
        internal static string StyleChooser_EmptyList_Label {
            get {
                return ResourceManager.GetString("StyleChooser_EmptyList_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Used Styles.
        /// </summary>
        internal static string StyleChooser_FavoriteStyleTitle_Label {
            get {
                return ResourceManager.GetString("StyleChooser_FavoriteStyleTitle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find citation style ....
        /// </summary>
        internal static string StyleChooser_InputSearch_Text {
            get {
                return ResourceManager.GetString("StyleChooser_InputSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Loading citation style preview ....
        /// </summary>
        internal static string StyleChooser_LoadingPreview_Label {
            get {
                return ResourceManager.GetString("StyleChooser_LoadingPreview_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a citation style.
        /// </summary>
        internal static string StyleChooser_NoStyleSelected_Label {
            get {
                return ResourceManager.GetString("StyleChooser_NoStyleSelected_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All citation styles supported by πFolio.
        /// </summary>
        internal static string StyleChooser_OfficialStyleAllTitle_Label {
            get {
                return ResourceManager.GetString("StyleChooser_OfficialStyleAllTitle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commonly Used Citation Styles.
        /// </summary>
        internal static string StyleChooser_OfficialStyleTitle_Label {
            get {
                return ResourceManager.GetString("StyleChooser_OfficialStyleTitle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;/head&gt;&lt;body style=&quot;font-family:Verdana;font-size:10px;&quot;&gt;&lt;p&gt;Familial clustering {0} of a disease is a direct indicator of a possible heritable cause, provided that environmental sharing can be excluded. If the familial clustering is lacking {1}, the likelihood of a heritable influence {2} is also all.&lt;br/&gt;&lt;/p&gt;&lt;p&gt;{3}&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string StyleChooser_Preview_Html {
            get {
                return ResourceManager.GetString("StyleChooser_Preview_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a citation style.
        /// </summary>
        internal static string StyleChooser_Title_Label {
            get {
                return ResourceManager.GetString("StyleChooser_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Citation Styles.
        /// </summary>
        internal static string StyleChooser_UserStyleTitle_Label {
            get {
                return ResourceManager.GetString("StyleChooser_UserStyleTitle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to πFolio - Citation style editor.
        /// </summary>
        internal static string StyleEditor_Title {
            get {
                return ResourceManager.GetString("StyleEditor_Title", resourceCulture);
            }
        }
    }
}
